name: The Mike Koene
favicon: null
layout_spectrum: 0.047044125851243734
typography_spectrum: 0.3725371619220823
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.694152929354459
  lightness: 0.678041543578729
  saturation: 0.24406668241135776
  rhythmicContrast: 0.6664419786538929
purpose: []
